// Generated by CoffeeScript 1.3.3
var OAuth, oa;

OAuth = require('oauth').OAuth;

oa = new OAuth("https://api.twitter.com/oauth/request_token", "https://api.twitter.com/oauth/access_token", "odLcgNdJ9HhtrBEEserw", "TTtca2mY2iHauZWjd7wVo4QEZVfDNfALnfTfbgkWoXs", "1.0", "http://127.0.0.1:3000/auth/twitter/callback", "HMAC-SHA1");

exports.auth_twitter = function(req, res) {
  console.log('start');
  oa.getOAuthRequestToken(function(error, oauth_token, oauth_token_secret, results) {
    if (error) {
      console.log('starterr');
      console.log(error);
      res.send("yeah no. didn't work.");
    } else {
      console.log('start2');
      req.session.oauth = {};
      req.session.oauth.token = oauth_token;
      console.log('start3');
      console.log('oauth.token: ' + req.session.oauth.token);
      req.session.oauth.token_secret = oauth_token_secret;
      console.log('oauth.token_secret: ' + req.session.oauth.token_secret);
      res.redirect('https://twitter.com/oauth/authenticate?oauth_token=' + oauth_token);
    }
  });
};

exports.auth_twitter_callback = function(req, res, next) {
  var oauth, year;
  year = 3600000 * 24 * 365;
  req.session.cookie.expires = new Date(Date.now() + year);
  req.session.cookie.maxAge = year;
  if (req.session.oauth) {
    req.session.oauth.verifier = req.query.oauth_verifier;
    oauth = req.session.oauth;
    return oa.getOAuthAccessToken(oauth.token, oauth.token_secret, oauth.verifier, function(error, oauth_access_token, oauth_access_token_secret, results) {
      if (error) {
        console.log(error);
        return res.send("yeah something broke.");
      } else {
        req.session.oauth.access_token = oauth_access_token;
        req.session.oauth.access_token_secret = oauth_access_token_secret;
        console.log(results);
        return res.send(req.session);
      }
    });
  } else {
    next(new Error("you're not supposed to be here."));
  }
};
